//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Albumtitles = new HashSet<Albumtitle>();
        }
    
        public int Id { get; set; }
        public string Albumname { get; set; }
        public Nullable<int> Releaseyear { get; set; }
        public string Coverpath { get; set; }
    
        public virtual ICollection<Albumtitle> Albumtitles { get; set; }
    }
}
