//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YAM_StorageEntities : DbContext
    {
        public YAM_StorageEntities()
            : base("name=YAM_StorageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album> Albums { get; set; }
        public DbSet<Albumtitle> Albumtitles { get; set; }
        public DbSet<Artist> Artists { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<Lang> Langs { get; set; }
        public DbSet<Lastsearch> Lastsearches { get; set; }
        public DbSet<Playlist> Playlists { get; set; }
        public DbSet<Playlistitem> Playlistitems { get; set; }
        public DbSet<Title> Titles { get; set; }
    }
}
