//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lang
    {
        public Lang()
        {
            this.Titles = new HashSet<Title>();
        }
    
        public int Id { get; set; }
        public string Langname { get; set; }
        public string Langcode { get; set; }
    
        public virtual ICollection<Title> Titles { get; set; }
    }
}
