//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public Title()
        {
            this.Albumtitles = new HashSet<Albumtitle>();
            this.Playlistitems = new HashSet<Playlistitem>();
            this.Artists = new HashSet<Artist>();
        }
    
        public int Id { get; set; }
        public string Titlename { get; set; }
        public Nullable<int> Genre { get; set; }
        public Nullable<int> Bitrate { get; set; }
        public Nullable<int> Releaseyear { get; set; }
        public long Playtime { get; set; }
        public Nullable<int> Lang { get; set; }
        public string Filepath { get; set; }
        public Nullable<System.DateTime> Lastplayed { get; set; }
        public Nullable<int> Playcounter { get; set; }
    
        public virtual ICollection<Albumtitle> Albumtitles { get; set; }
        public virtual Genre Genre1 { get; set; }
        public virtual Lang Lang1 { get; set; }
        public virtual ICollection<Playlistitem> Playlistitems { get; set; }
        public virtual ICollection<Artist> Artists { get; set; }
    }
}
